#!/usr/bin/env bash
protected_branch='master'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $protected_branch = $current_branch ]
    then
        echo "Running pre-push unit tests..."
        ./scripts/unittest.sh

        # $? stores exit value of the last command
        if [ $? -ne 0 ]; then
            echo "Unit tests must pass..."
            exit 1
        fi

        echo "Running pre-push style checks on the main program..."
        flake8 main.py

        echo "Running pre-push style checks on source code..."
        flake8 src/*.py

        # $? stores exit value of the last command
        if [ $? -ne 0 ]; then
            echo "Style checks must pass on source code..."
            exit 1
        fi

        echo "Running pre-push style checks on unit tests..."
        flake8 test/*.py

        # $? stores exit value of the last command
        if [ $? -ne 0 ]; then
            echo "Style checks must pass on unit tests..."
            exit 1
        fi

else
    exit 0
fi